version: '3.5'
services:

  postgres:
    image: docker.io/postgres:15-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: authjs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
